# general info
agent:
  name: appointment_selector
  protocol: rasa
  description: Helps users select an appointment slot for seeing a car dealer.

# Core agent configuration
configuration:
  module: custom.appointment_booking_agent.AppointmentBookingAgent
  prompt_template: ./sub_agents_docker_compose/appointment_selector/prompt_template.jinja2

# Integrations
connections:
  mcp_servers:
    - name: appointment_booking
      exclude_tools:
        - book_appointment
