agent:
  name: research_new_cars
  protocol: mcp
  description: "Helps users research the web to find new cars according to their preferences"

configuration:
  prompt_template: ./sub_agents/research_agent/prompt_template.jinja2
  module: custom.car_research_agent.CarResearchAgent

connections:
  mcp_servers:
    - name: tavily_search
