# The config recipe.
recipe: default.v1
language: en

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250711-005358-oscillating-volcano

pipeline:
- name: SearchReadyLLMCommandGenerator
  llm:
    model_group: openai-gpt-5-1
  flow_retrieval:
    active: false

# Configuration for Rasa Core.
policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
  llm:
    model_group: openai-gpt-5-1
  embeddings:
    model_group: openai-embeddings
  vector_store:
    type: faiss
    source: ./docs
  citation_enabled: true
  check_relevancy: true
